---
title: "webscraping"
author: "Rumo Schilling"
date: "2023-02-23"
output: html_document
---
```{r}
library(robotstxt)
library(tidyverse)
library(rvest)
library(stringr)
library(XML)
library(downloader)
library(htmltools)
page <- read_html("https://www.imdb.com/chart/top")
typeof(page)
save_html(page,"RumoDS")
```
```{r}
titles <-page %>%
  html_nodes(".titleColumn a")%>%
  html_text()
years <-page %>%
  html_nodes(".secondaryInfo")%>%
  html_text()%>%
  str_remove("\\(")%>%
  str_remove("\\)")%>%
  as.numeric()
ratings<-page %>% 
  html_nodes("strong")%>% 
  html_text()%>%
  as.numeric()
imdb <- tibble(
  title = titles,
  year = years,
  rating = ratings
)
imdb 
```
```{r}
page = read_html("http://facepage.putneyschool.org")
names<- page %>%
  html_nodes(".studentName")%>%
  html_text()
names
```
```{r}
#| label: the top countries

wikipage = read_html("https://en.wikipedia.org/wiki/World_population")
s
wikipage %>%
   html_nodes("table") %>% 
  `[[`(3) %>%
  html_table()
wikipage %>%
  html_nodes("a")%>%
  '[['(2) %>%
  html_text()
wikipage %>%
  html_nodes("a")%>%
  html_text()
```
```{r}
testlink = read_html("https://www.openintro.org/data/index.php?data=absenteeism")
testlink %>%
  html_nodes("p:nth-child(7)")%>%
  html_text() %>%
  str_split_i("with ",2)%>%
  str_split_i(" observations",1)
  # testlink %>%
    # html_nodes("p") %>%
    # '[['(4) %>%
    # html_text() %>%
    # str_replace_all(pattern= "\n",replacement = " ")
```
```{r}
openintro <-read_html("https://www.openintro.org/data/")
links  <-openintro %>%
  html_nodes(".h5 a") %>%
  html_attr("href")
titles <-openintro %>%
  html_nodes(".h5 a") %>%
  html_text()
descriptions <- c()
for (x in 1:length(links)) {
  filename<-paste(titles[x],".html",sep = "")
  download(paste("https://www.openintro.org/data/",links[x],sep = ""), filename)
  Sys.sleep(2)
}
```

```{r}
for (title in titles)
{
  page = read_html(paste(title,".html",sep = ""))
  # observation <-html_nodes("p:nth-child(7)")%>%
  # html_text() %>%
  # str_split_i("with ",2)%>%
  # str_split_i(" observations",1)

  description <- page %>%
    html_nodes("p:nth-child(3)") %>%
    html_text() %>%
    str_replace_all(pattern= "\n",replacement = " ")
  descriptions %>%append(description)
}
descriptions


```